/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mgkcmohjjzqsrnkmchsv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1na2Ntb2hqanpxc3Jua21jaHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5OTE3MzgsImV4cCI6MjA4MTU2NzczOH0.Pc0U7hm-Pks_9m_YDZOAL1jgWoP-qSBgaKLKiJFf9gw"